#!/bin/sh -e
### BEGIN INIT INFO
# PROVIDES:		shim_svc
# REQUIRED-START:
# REQUIRED-STOP:
# DEFAULT-START: 2 3 4 5
# DEFAULT-STOP:  0 1 6
# Short-Description: Dev Mon data shim
# Description: Provides DevMon data ingestion for firewalls running PAN-OS 8.0 and earlier
#### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
DIR=/usr/local/bin
DAEMON=$DIR/pan_shim.py
DAEMON_NAME=shim_svc

DAEMON_OPTS=""

DAEMON_USER=root

PIDFILE=/var/run/$DAEMON_NAME

. /lib/lsb/init-functions


do_start () {
	log_daemon_msg "Starting system $DAEMON_NAME daemon"
	start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --exec $DAEMON
	log_end_msg $?
}
do_stop () {
	log_daemon_msg "Stopping system $DAEMON_NAME daemon"
	start-stop-daemon --stop --pidfile $PIDFILE --remove-pidfile --retry 10
	log_end_msg $?
}

case "$1" in
	start)
		do_start
		;;

	stop)
		do_stop
		;;

	restart|reload|force-reload)
		do_stop
		do_start
		;;

	status)
		status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
		;;

	*)
		echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
		exit 1
		;;

esac
exit 0
